Fix linking with modern compilers
Since static libAAF depends on libsndfile and does not
link against libsndfile itself it needs to be listed first.

This fixes `AAFIAudioFiles.c undefined reference to `sf_*'
errors.